spring.application.name=Clean Architecture

# allow all actuator tools
management.endpoints.web.exposure.include=*

spring.mvc.apiversion.supported=1.0,2.0
spring.mvc.apiversion.default=1.0
#index of the version in the path /v1/users
spring.mvc.apiversion.use.path-segment=0